# Generated by Django 5.1.2 on 2024-11-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arpspoofer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoofer',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
