# Generated by Django 5.1.2 on 2024-10-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snifferAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
