# Generated by Django 5.1.2 on 2024-10-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snifferAPI', '0002_alter_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='running',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(blank=True, default='test sniffer', max_length=50, null=True),
        ),
    ]
